// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TitanFitenss.Infrastructure.Persistence;

#nullable disable

namespace TitanFitenss.Infrastructure.Migrations
{
    [DbContext(typeof(TitanFitnessDbContext))]
    [Migration("20260903012327_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TitanFitenss.Domain.BranchAggregate.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ClosingTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OpeningTime")
                        .HasColumnType("datetime2");

                    b.HasKey("BranchId");

                    b.ToTable("Branches", (string)null);
                });

            modelBuilder.Entity("TitanFitenss.Domain.BranchAggregate.Studio", b =>
                {
                    b.Property<int>("StudioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudioId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("StudioName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudioId");

                    b.HasIndex("BranchId");

                    b.ToTable("Studio");
                });

            modelBuilder.Entity("TitanFitenss.Domain.CheckInAggregate.CheckIn", b =>
                {
                    b.Property<int>("CheckInId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckInId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckInDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("RefusalReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.HasKey("CheckInId");

                    b.ToTable("CheckIns", (string)null);
                });

            modelBuilder.Entity("TitanFitenss.Domain.ClassSessionAggregate.ClassSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CapacityLimit")
                        .HasColumnType("int");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudioId")
                        .HasColumnType("int");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.ToTable("ClassSessions", (string)null);
                });

            modelBuilder.Entity("TitanFitenss.Domain.MemberAggregate.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HomeBranchId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("JoinDate")
                        .HasColumnType("date");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MembershipNumber");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.HasIndex("MembershipNumber")
                        .IsUnique();

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("TitanFitenss.Domain.MembershipAggregate.Membership", b =>
                {
                    b.Property<int>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembershipId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MembershipId");

                    b.ToTable("Memberships", (string)null);
                });

            modelBuilder.Entity("TitanFitenss.Domain.PlanAggregate.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<int>("AccessScope")
                        .HasColumnType("int");

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("int");

                    b.Property<int>("GuestPassQuota")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("MaxFreezeDays")
                        .HasColumnType("int");

                    b.Property<int>("MaxNumberOfFreezes")
                        .HasColumnType("int");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("PlanId");

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("TitanFitenss.Domain.TrainerAggregate.Trainer", b =>
                {
                    b.Property<int>("TrainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrainerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TrainerId");

                    b.ToTable("Trainers", (string)null);
                });

            modelBuilder.Entity("TitanFitenss.Domain.BranchAggregate.Branch", b =>
                {
                    b.OwnsOne("TitanFitenss.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("BranchId")
                                .HasColumnType("int");

                            b1.Property<int>("ApartmentNumber")
                                .HasMaxLength(3)
                                .HasColumnType("int")
                                .HasColumnName("ApartmentNumber");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("City");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(97)
                                .HasColumnType("nvarchar(97)")
                                .HasColumnName("Street");

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("TitanFitenss.Domain.BranchAggregate.Studio", b =>
                {
                    b.HasOne("TitanFitenss.Domain.BranchAggregate.Branch", "Branch")
                        .WithMany("Studios")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("TitanFitenss.Domain.ClassSessionAggregate.ClassSession", b =>
                {
                    b.OwnsMany("TitanFitenss.Domain.ClassSessionAggregate.Booking", "Bookings", b1 =>
                        {
                            b1.Property<int>("BookingId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("BookingId"));

                            b1.Property<DateTime>("BookedOn")
                                .HasColumnType("datetime2");

                            b1.Property<int>("MemberId")
                                .HasColumnType("int");

                            b1.Property<string>("NotesForTrainer")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<int>("SessionId")
                                .HasColumnType("int");

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.Property<int?>("WaitlistPosition")
                                .HasColumnType("int");

                            b1.HasKey("BookingId");

                            b1.HasIndex("SessionId");

                            b1.ToTable("Bookings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("TitanFitenss.Domain.MemberAggregate.Member", b =>
                {
                    b.OwnsOne("TitanFitenss.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("MemberId")
                                .HasColumnType("int");

                            b1.Property<int>("ApartmentNumber")
                                .HasMaxLength(3)
                                .HasColumnType("int")
                                .HasColumnName("ApartmentNumber");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("City");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(97)
                                .HasColumnType("nvarchar(97)")
                                .HasColumnName("Street");

                            b1.HasKey("MemberId");

                            b1.ToTable("Members");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("TitanFitenss.Domain.MembershipAggregate.Membership", b =>
                {
                    b.OwnsOne("TitanFitenss.Domain.MembershipAggregate.AgreedTerms", "AgreedTerms", b1 =>
                        {
                            b1.Property<int>("MembershipId")
                                .HasColumnType("int");

                            b1.Property<int>("AccessScope")
                                .HasColumnType("int");

                            b1.Property<int>("DurationInMonths")
                                .HasColumnType("int")
                                .HasColumnName("DurationInMonths");

                            b1.Property<int>("GuestPassQuota")
                                .HasColumnType("int")
                                .HasColumnName("GuestPassQuota");

                            b1.Property<int>("MaxFreezeDays")
                                .HasColumnType("int")
                                .HasColumnName("MaxFreezeDays");

                            b1.Property<int>("MaxNumberOfFreezeDays")
                                .HasColumnType("int")
                                .HasColumnName("MaxNumberOfFreezes");

                            b1.Property<decimal>("PricePaid")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("PricePaid");

                            b1.HasKey("MembershipId");

                            b1.ToTable("Memberships");

                            b1.WithOwner()
                                .HasForeignKey("MembershipId");
                        });

                    b.OwnsMany("TitanFitenss.Domain.MembershipAggregate.Freeze", "Freezes", b1 =>
                        {
                            b1.Property<int>("FreezeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("FreezeId"));

                            b1.Property<string>("AdditionalNotes")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<int>("DurationInMonths")
                                .HasColumnType("int");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("date");

                            b1.Property<int>("MembershipId")
                                .HasColumnType("int");

                            b1.Property<int>("Reason")
                                .HasColumnType("int");

                            b1.Property<DateTime>("RequestedOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("date");

                            b1.HasKey("FreezeId");

                            b1.HasIndex("MembershipId");

                            b1.ToTable("Freezes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MembershipId");
                        });

                    b.OwnsMany("TitanFitenss.Domain.MembershipAggregate.GuestPass", "GuestPasses", b1 =>
                        {
                            b1.Property<int>("GuestPassId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("GuestPassId"));

                            b1.Property<string>("GuestName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<DateTime>("IssuedOn")
                                .HasColumnType("date");

                            b1.Property<int>("MembershipId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("UsedOn")
                                .HasColumnType("date");

                            b1.HasKey("GuestPassId");

                            b1.HasIndex("MembershipId");

                            b1.ToTable("GuestPasses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MembershipId");
                        });

                    b.Navigation("AgreedTerms")
                        .IsRequired();

                    b.Navigation("Freezes");

                    b.Navigation("GuestPasses");
                });

            modelBuilder.Entity("TitanFitenss.Domain.BranchAggregate.Branch", b =>
                {
                    b.Navigation("Studios");
                });
#pragma warning restore 612, 618
        }
    }
}
